In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv('G:\DATASETS FIR DSMP\imdb-top-1000.csv')
movies.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\User\AppData\Local\Temp\ipykernel_24632\3518942549.py:1: SyntaxWarning: invalid escape sequence '\D'
  movies=pd.read_csv('G:\DATASETS FIR DSMP\imdb-top-1000.csv')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [12]:
#group by  is very powerfull function which we will apply in the data.in data we have two types of data in which one is numerical and the other is catagorical data so when we are group by function then we apply it in our catagorical data
#now we are going to apply this on our data above

In [38]:
genres = movies.groupby('Genre')

In [37]:
# Group by "Genre" but keep only numeric columns
df = pd.DataFrame(movies) 
std_result = df.groupby("Genre")[["IMDB_Rating", "No_of_Votes", "Gross", "Metascore"]].mean()

print(std_result)

           IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action        7.949419  420246.581395  1.897224e+08  73.419580
Adventure     7.937500  313557.819444  1.319017e+08  78.437500
Animation     7.930488  268032.073171  1.784326e+08  81.093333
Biography     7.938636  272805.045455  9.404952e+07  76.240506
Comedy        7.901290  178195.658065  1.010572e+08  78.720000
Crime         8.016822  313398.271028  7.899656e+07  77.080460
Drama         7.957439  212343.612457  1.225259e+08  79.701245
Family        7.800000  275610.500000  2.195553e+08  79.000000
Fantasy       8.000000   73111.000000  3.913633e+08        NaN
Film-Noir     7.966667  122405.000000  4.197018e+07  95.666667
Horror        7.909091  340232.363636  9.405902e+07  80.000000
Mystery       7.975000  350250.333333  1.047014e+08  79.125000
Thriller      7.800000   27733.000000  1.755074e+07  81.000000
Western       8.350000  322416.250000  1.455538e+07  78.250000

In [36]:
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [ ]:
genres.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [12]:
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [33]:
#find the top income movies
genres.sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [42]:
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [47]:
#find the director with most popular
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [48]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [49]:
#find the number of movies each actor did
movies['Star1'].value_counts()

Star1
Tom Hanks          12
Robert De Niro     11
Al Pacino          10
Clint Eastwood     10
Humphrey Bogart     9
                   ..
Preity Zinta        1
Javier Bardem       1
Ki-duk Kim          1
Vladimir Garin      1
Robert Donat        1
Name: count, Length: 660, dtype: int64

In [ ]:
# GroupBy Attributes and Methods
# find total number of groups -> len
# find items in each group -> size
# first()/last() -> nth item
# get_group -> vs filtering
# groups
# describe
# sample
# nunique

In [53]:
#for checking the length of group that in our data how much groups made
len(movies.groupby('Genre'))

14

In [55]:
#if we want to check the size of each grup in our data then we will use size function
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [57]:
#first and last of each function
movies.groupby('Genre').first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [58]:
movies.groupby('Genre').last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [ ]:
#nth function is used for the check the result on the base of the specific colulms lets supoose  i need the result of the specific colums of any groups  i used its nth functions
movies.groupby('Genre').nth(7)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
28,The Silence of the Lambs,1991,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922.0,85.0
29,Star Wars,1977,121,Action,8.6,George Lucas,Mark Hamill,1231473,322740140.0,90.0
34,Whiplash,2014,106,Drama,8.5,Damien Chazelle,Miles Teller,717585,13092000.0,88.0
70,Mononoke-hime,1997,134,Animation,8.4,Hayao Miyazaki,Yôji Matsuda,343171,2375308.0,76.0
95,Amélie,2001,122,Comedy,8.3,Jean-Pierre Jeunet,Audrey Tautou,703810,33225499.0,69.0
107,Amadeus,1984,160,Biography,8.3,Milos Forman,F. Murray Abraham,369007,51973029.0,88.0
137,Queen,2013,146,Adventure,8.2,Vikas Bahl,Kangana Ranaut,60701,1429534.0,NaN
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0

In [62]:
genres.get_group('Fantasy')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [64]:
genres.get_group('Thriller')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [65]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [66]:
genres.sample()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
784,The Last Samurai,2003,154,Action,7.7,Edward Zwick,Tom Cruise,400049,111110575.0,55.0
984,The Muppet Movie,1979,95,Adventure,7.6,James Frawley,Jim Henson,32802,76657000.0,74.0
219,Song of the Sea,2014,93,Animation,8.1,Tomm Moore,David Rawle,51679,857524.0,85.0
228,Hachi: A Dog's Tale,2009,93,Biography,8.1,Lasse Hallström,Richard Gere,253575,91090444.0,NaN
842,Airplane!,1980,88,Comedy,7.7,Jim Abrahams,David Zucker,214882,83400000.0,78.0
28,The Silence of the Lambs,1991,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922.0,85.0
936,Un long dimanche de fiançailles,2004,133,Drama,7.6,Jean-Pierre Jeunet,Audrey Tautou,70925,6167817.0,76.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
393,Twelve Monkeys,1995,129,Mystery,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

In [ ]:
#if we want to check randomly more movies then we apply samples with specific value
#in this we will do replace true.by doing replace true will enable result if any type of movie have less movies thean the given movies and give us not error if it will not true it will show us error
genres.sample(3,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
928,300,2006,117,Action,7.6,Zack Snyder,Gerard Butler,732876,210614939.0,52.0
666,Lat sau san taam,1992,128,Action,7.8,John Woo,Yun-Fat Chow,46700,565451439.0,NaN
642,The Count of Monte Cristo,2002,131,Action,7.8,Kevin Reynolds,Jim Caviezel,129022,54234062.0,61.0
638,Diarios de motocicleta,2004,126,Adventure,7.8,Walter Salles,Gael García Bernal,96703,16756372.0,75.0
798,Interstate 60: Episodes of the Road,2002,116,Adventure,7.7,Bob Gale,James Marsden,29999,174381905.0,NaN
781,Harry Potter and the Goblet of Fire,2005,157,Adventure,7.7,Mike Newell,Daniel Radcliffe,548619,290013036.0,81.0
822,Kurenai no buta,1992,94,Animation,7.7,Hayao Miyazaki,Shûichirô Moriyama,77798,871544815.0,83.0
592,Big Hero 6,2014,102,Animation,7.8,Don Hall,Chris Williams,410983,222527828.0,74.0
740,Wreck-It Ralph,2012,101,Animation,7.7,Rich Moore,John C. Reilly,380195,189422889.0,72.0
139,Bhaag Milkha Bhaag,2013,186,Biography,8.2,Rakeysh Omprakash Mehra,Farhan Akhtar,61137,1626289.0,NaN
882,Just Mercy,2019,137,Biography,7.6,Destin Daniel Cretton,Michael B. Jordan,46739,279498224.0,68.0
649,The Insider,1999,157,Biography,7.8,Michael Mann,Russell Crowe,159886,28965197.0,84.0
558,Miracle on 34th Street,1947,96,Comedy,7.9,George Seaton,Edmund Gwenn,41625,2650000.0,88.0
727,What We Do in the Shadows,2014,86,Comedy,7.7,Jemaine Clement,Taika Waititi,157498,3333000.0,76.0
327,La La Land,2016,128,Comedy,8.0,Damien Chazelle,Ryan Gosling,505918,151101803.0,94.0
833,Der Name der Rose,1986,130,Crime,7.7,Jean-Jacques Annaud,Sean Connery,102031,7153487.0,54.0
603,The Girl with the Dragon Tattoo,2011,158,Crime,7.8,David Fincher,Daniel Craig,423010,102515793.0,71.0
222,Prisoners,2013,153,Crime,8.1,Denis Villeneuve,Hugh Jackman,601149,61002302.0,70.0
572,Forushande,2016,124,Drama,7.8,Asghar Farhadi,Shahab Hosseini,51240,2402067.0,85.0
736,The Broken Circle Breakdown,2012,111,Drama,7.7,Felix van Groeningen,Veerle Baetens,39379,175058.0,70.0
787,In America,2002,105,Drama,7.7,Jim Sheridan,Paddy Considine,40403,15539266.0,76.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
393,Twelve Monkeys,1995,129,Mystery,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
145,Shutter Island,2010,138,Mystery,8.2,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0,63.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [ ]:
#it wll give us unique values counts
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [79]:
#it will use to get agregation mean in which colum which function we want to do or in same time we will do it multiple function by using it
genres.aggregate(
    {
    'Runtime':'mean',
        'IMDB_Rating':'mean',
        'No_of_Votes':'sum',
        'Gross':'sum',
        'Metascore':'min' 
}  
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [81]:
# Adding both the syntax
genres.agg(
    {
        'Runtime':['min','mean'],
        'IMDB_Rating':'mean',
        'No_of_Votes':['sum','max'],
        'Gross':'sum',
        'Metascore':'min'
    }
)

          Runtime             IMDB_Rating No_of_Votes                  Gross  \
              min        mean        mean         sum      max           sum
Genre
Action         45  129.046512    7.949419    72282412  2303232  3.263226e+10
Adventure      88  134.111111    7.937500    22576163  1512360  9.496922e+09
Animation      71   99.585366    7.930488    21978630   999790  1.463147e+10
Biography      93  136.022727    7.938636    24006844  1213505  8.276358e+09
Comedy         68  112.129032    7.901290    27620327   939631  1.566387e+10
Crime          80  126.392523    8.016822    33533615  1826188  8.452632e+09
Drama          64  124.737024    7.957439    61367304  2343110  3.540997e+10
Family        100  107.500000    7.800000      551221   372490  4.391106e+08
Fantasy        76   85.000000    8.000000      146222    88794  7.827267e+08
Film-Noir     100  104.000000    7.966667      367215   158731  1.259105e+08
Horror         71  102.090909    7.909091     3742556   787806  1.034649e+09
Mystery        96  119.083333    7.975000     4203004  1129894  1.256417e+09
Thriller      108  108.000000    7.800000       27733    27733  1.755074e+07
Western       132  148.250000    8.350000     1289665   688390  5.822151e+07

          Metascore
                min
Genre
Action         33.0
Adventure      41.0
Animation      61.0
Biography      48.0
Comedy         45.0
Crime          47.0
Drama          28.0
Family         67.0
Fantasy         NaN
Film-Noir      94.0
Horror         46.0
Mystery        52.0
Thriller       81.0
Western        69.0

In [85]:
import pandas as pd
import numpy as np

In [98]:
#highest rating movies in the file
# looping on groups
import pandas as pd
df = pd.DataFrame(columns=movies.columns)
for group,data in genres:
  df = pd.concat([df,data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]])

df

C:\Users\User\AppData\Local\Temp\ipykernel_24632\1857552572.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df,data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]])

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [100]:
genres.apply(min)

C:\Users\User\AppData\Local\Temp\ipykernel_24632\1443917609.py:1: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)
C:\Users\User\AppData\Local\Temp\ipykernel_24632\1443917609.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [101]:
# groupby on multiple cols
duo = movies.groupby(['Director','Star1'])
duo

In [102]:
duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [117]:
duo.agg('min')

                                                  Series_Title Released_Year  \
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par          2007
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7          2020
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle          2013
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab          2016
Abhishek Kapoor     Amit Sadh                      Kai po che!          2013
...                                                        ...           ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid          2013
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara          2011
                    Vijay Varma                      Gully Boy          2019
Çagan Irmak         Çetin Tekindor              Babam ve Oglum          2005
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.          2004

                                    Runtime      Genre  IMDB_Rating  \
Director            Star1
Aamir Khan          Amole Gupte         165      Drama          8.4
Aaron Sorkin        Eddie Redmayne      129      Drama          7.8
Abdellatif Kechiche Léa Seydoux         180      Drama          7.7
Abhishek Chaubey    Shahid Kapoor       148     Action          7.8
Abhishek Kapoor     Amit Sadh           130      Drama          7.7
...                                     ...        ...          ...
Zaza Urushadze      Lembit Ulfsak        87      Drama          8.2
Zoya Akhtar         Hrithik Roshan      155     Comedy          8.1
                    Vijay Varma         154      Drama          8.0
Çagan Irmak         Çetin Tekindor      112      Drama          8.3
Ömer Faruk Sorak    Cem Yilmaz          127  Adventure          8.0

                                    No_of_Votes        Gross  Metascore
Director            Star1
Aamir Khan          Amole Gupte          168895    1223869.0        NaN
Aaron Sorkin        Eddie Redmayne        89896  853090410.0       77.0
Abdellatif Kechiche Léa Seydoux          138741    2199675.0       89.0
Abhishek Chaubey    Shahid Kapoor         27175  218428303.0        NaN
Abhishek Kapoor     Amit Sadh             32628    1122527.0       40.0
...                                         ...          ...        ...
Zaza Urushadze      Lembit Ulfsak         40382     144501.0       73.0
Zoya Akhtar         Hrithik Roshan        67927    3108485.0        NaN
                    Vijay Varma           31886    5566534.0       65.0
Çagan Irmak         Çetin Tekindor        78925  461855363.0        NaN
Ömer Faruk Sorak    Cem Yilmaz            56960  196206077.0        NaN

[898 rows x 8 columns]